name: Security

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Dependency Scan
      uses: anchore/scan-action@master
      with:
        image-reference: "joeyx22lm/docker-github-actions-runner:alpha"
        fail-build: true
