name: Publish Alpha Docker Image

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: manusa/actions-publish-docker@master
      with:
        name: joeyx22lm/docker-github-actions-runner
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: alpha
