name: Package Release

on:
  push:
    branches: master
    tags: v*.*.*

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image
        run: docker build -t image .

      - name: Authenticate with DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker tag image ${{ github.repository }}:$VERSION
          docker tag image ${{ github.repository }}:latest
          docker push ${{ github.repository }}:$VERSION
          docker push ${{ github.repository }}:latest

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Dependency Scan
      uses: anchore/scan-action@master
      with:
        image-reference: "${{ github.repository }}:latest"
        fail-build: true
