name: Functional Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image
        run: docker build -t image .

      - name: Run All Tests
        run: |
          .github/workflows/resources/tests.sh "${{ github.repository }}" "${{ secrets.TestRunnerToken }}" "${{ github.sha }}"
